name: kevins
favicon: null
layout_spectrum: 0.50078
typography_spectrum: 0.5341993502806872
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#dbdbdb'
    - '#404040'
    - '#707070'
  brandStrength: 0.5
  lightness: 0.7298564754892141
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
